apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-sealedsecret.yaml
  - backend-sealedsecret.yaml
  - cloudflared-sealedsecret.yaml
  - discord-sealedsecret.yaml
namespace: blackvoxel
commonLabels:
  app: common
