apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackvoxel-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drme-bit/blackvoxel-infra
    targetRevision: staging
    path: envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: blackvoxel-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
