apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackvoxel-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drme-bit/blackvoxel-infra
    targetRevision: prod
    path: envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: blackvoxel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
