tunnel: blackvoxel
credentials-file: /etc/cloudflared/credentials.json
warp-routing:
  enabled: true
ingress:
  - hostname: blackvoxel.studio
    service: http://frontend.blackvoxel.svc.cluster.local:80 # ВСЁ на frontend

  - hostname: api.blackvoxel.studio
    service: http://backend.blackvoxel.svc.cluster.local:8080 # ВСЁ на backend

  - service: http_status:404
