tunnel: blackvoxel
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: blackvoxel.studio
    path: /api/*
    service: http://backend.blackvoxel.svc.cluster.local:8080
  - hostname: blackvoxel.studio
    service: http://frontend.blackvoxel.svc.cluster.local:3000

  - service: http_status:404
